
language: ruby
rvm:
- 2.6.3
​
before_script:
- openssl aes-256-cbc -K $encrypted_9b2d7e19d83c_key -iv $encrypted_9b2d7e19d83c_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 35.220.143.170\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
​
install:
- gem install jekyll
- gem install jekyll-paginate
​
script:
- bundle install
- jekyll build #&& htmlproofer ./_site
​
after_success:
  - ssh root@35.220.143.170 -p 22 -o StrictHostKeyChecking=no "rm -rf /data/www/pingos.io"
  - scp -r _site root@35.220.143.170:/data/www/pingos.io

# branch whitelist, only for Github Pages
branchs:
  only:
  - master
​
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
​
addons:
  ssh_known_hosts:
  - 35.220.143.170
​
sudo: false